name: SunnyPilot CI

env:
  BUILD_DIR: "/data/openpilot"
  OUTPUT_DIR: ${{ github.workspace }}/output
  CI_DIR: ${{ github.workspace }}/release/ci
  BASE_BUILD_NUMBER: 3000
  PUBLIC_REPO_URL: "https://github.com/sunnyhaibin/sunnypilot"
  DEV_C3_SOURCE_BRANCH: "master-dev-c3"

on:
  push:
    branches: [ master, master-new, master-dev-c3, kumar-wants-gitlab-prebuilt ]
    tags: [ '*' ]
  pull_request:
    branches: [ master, master-new ]
  workflow_dispatch:
    inputs:
      extra_version:
        description: 'Extra version identifier'
        required: false
        default: ''

jobs:
  build:
    runs-on: self-hosted
    if: |
      !contains(github.event.head_commit.message, 'wip:') && 
      !contains(github.event.head_commit.message, 'draft:')
    
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set environment variables
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "NEW_BRANCH=${GITHUB_REF_NAME}-prebuilt" >> $GITHUB_ENV
            echo "EXTRA_VERSION_IDENTIFIER=${{ github.event.inputs.extra_version || github.run_number }}" >> $GITHUB_ENV
            echo "VERSION=$(date '+%Y.%m.%d')" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" == "${{ env.DEV_C3_SOURCE_BRANCH }}" ]]; then
            echo "NEW_BRANCH=dev-c3" >> $GITHUB_ENV
            echo "EXTRA_VERSION_IDENTIFIER=${{ github.run_number }}" >> $GITHUB_ENV
            echo "AUTO_BUILD=true" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
            echo "NEW_BRANCH=staging-c3" >> $GITHUB_ENV
            echo "EXTRA_VERSION_IDENTIFIER=staging" >> $GITHUB_ENV
            echo "AUTO_BUILD=true" >> $GITHUB_ENV
            echo "AUTO_PUBLISH=true" >> $GITHUB_ENV
            echo "VERSION=$(cat common/version.h | grep COMMA_VERSION | sed -e 's/[^0-9|.]//g')" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == refs/tags/* ]]; then
            echo "NEW_BRANCH=release-c3" >> $GITHUB_ENV
            echo "EXTRA_VERSION_IDENTIFIER=release" >> $GITHUB_ENV
            echo "AUTO_BUILD=true" >> $GITHUB_ENV
            echo "VERSION=$(cat common/version.h | grep COMMA_VERSION | sed -e 's/[^0-9|.]//g')" >> $GITHUB_ENV
          else
            echo "VERSION=$(date '+%Y.%m.%d')-${{ github.run_number }}" >> $GITHUB_ENV
          fi

      - name: Setup build environment
        run: |
          mkdir -p "${BUILD_DIR}/"
          find $BUILD_DIR/ -mindepth 1 -delete
          echo "Starting build stage..."
          echo "BUILD_DIR: ${BUILD_DIR}"
          echo "CI_DIR: ${CI_DIR}"
          echo "VERSION: ${VERSION}"

      - name: Build Panda
        run: |
          scons -j$(nproc) cache_dir=${CI_DIR}/scons_cache ${{ github.workspace }}/panda

      - name: Build Main Project
        run: |
          export PYTHONPATH="$BUILD_DIR"
          ./release/release_files.py | sort | uniq | rsync -vrRl --files-from=- . $BUILD_DIR/
          cd $BUILD_DIR
          sed -i '/from .board.jungle import PandaJungle, PandaJungleDFU/s/^/#/' panda/__init__.py
          scons -j$(nproc) cache_dir=${CI_DIR}/scons_cache --minimal
          touch ${BUILD_DIR}/prebuilt

      - name: Prepare Output
        run: |
          sudo rm -rf ${OUTPUT_DIR}
          mkdir -p ${OUTPUT_DIR}
          rsync -avm \
            --include='**/panda/board/' \
            --include='**/panda/board/obj' \
            --include='**/panda/board/obj/panda.bin.signed' \
            --include='**/panda/board/obj/panda_h7.bin.signed' \
            --include='**/panda/board/obj/bootstub.panda.bin' \
            --include='**/panda/board/obj/bootstub.panda_h7.bin' \
            --exclude='.sconsign.dblite' \
            --exclude='*.a' \
            --exclude='*.o' \
            --exclude='*.os' \
            --exclude='*.pyc' \
            --exclude='moc_*' \
            --exclude='*.cc' \
            --exclude='Jenkinsfile' \
            --exclude='supercombo.onnx' \
            --exclude='**/panda/board/*' \
            --exclude='**/panda/board/obj/**' \
            --exclude='**/panda/certs/' \
            --exclude='**/panda/crypto/' \
            --exclude='**/release/' \
            --exclude='**/.github/' \
            --exclude='**/selfdrive/ui/replay/' \
            --exclude='**/__pycache__/' \
            --exclude='**/selfdrive/ui/*.h' \
            --exclude='**/selfdrive/ui/**/*.h' \
            --exclude='**/selfdrive/ui/qt/offroad/sunnypilot/' \
            --exclude='**/.git/' \
            --exclude='**/SConstruct' \
            --exclude='**/SConscript' \
            --delete-excluded \
            --chown=comma:comma \
            ${BUILD_DIR}/ ${OUTPUT_DIR}/

      - name: Cache SCons
        uses: actions/cache@v4
        with:
          path: ${{ env.CI_DIR }}/scons_cache
          key: ${{ runner.os }}-scons-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-scons-

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: ${{ env.OUTPUT_DIR }}

  publish-private:
    needs: build
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'workflow_dispatch' ||
      github.event_name == 'pull_request' ||
      env.AUTO_BUILD == 'true'
    
    steps:
      - uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4.1.7
        with:
          name: build-output
          path: ${{ env.OUTPUT_DIR }}

      - name: Configure Git
        run: |
          git config --global user.email "gitlab@pipeline.com"
          git config --global user.name "Github Pipeline"

      - name: Publish to Private Repository
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITLAB_SSH_KEY }}
        run: |
          eval $(ssh-agent -s)
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -H gitlab.com >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          
          ${{ env.CI_DIR }}/publish.sh \
            "${{ github.workspace }}" \
            "${{ env.OUTPUT_DIR }}" \
            "${{ env.NEW_BRANCH }}" \
            "${{ env.VERSION }}" \
            "git@gitlab.com:sunnypilot/public/sunnypilot-prebuilts.git" \
            "-${{ env.EXTRA_VERSION_IDENTIFIER }}"

  publish-public:
    needs: build
    runs-on: ubuntu-latest
    if: |
      env.AUTO_PUBLISH == 'true' ||
      github.event_name == 'workflow_dispatch'
    environment: manual-approval
    
    steps:
      - uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4.1.7
        with:
          name: build-output
          path: ${{ env.OUTPUT_DIR }}

      - name: Configure Git
        run: |
          git config --global user.email "jason.wen@sunnypilot.ai"
          git config --global user.name "Jason Wen"

      - name: Publish to Public Repository
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITHUB_SSH_KEY }}
        run: |
          eval $(ssh-agent -s)
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          
          ${{ env.CI_DIR }}/publish.sh \
            "${{ github.workspace }}" \
            "${{ env.OUTPUT_DIR }}" \
            "${{ env.NEW_BRANCH }}" \
            "${{ env.VERSION }}" \
            "git@github.com:sunnyhaibin/sunnypilot.git" \
            "-${{ env.EXTRA_VERSION_IDENTIFIER }}"

  notify:
    needs: [publish-private, publish-public]
    runs-on: ubuntu-latest
    if: always() && env.NEW_BRANCH != ''
    
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq gettext-base

      - name: Send Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ env.NEW_BRANCH == 'dev-c3' && secrets.DISCORD_NEW_BUILD_WEBHOOK_URL || secrets.DISCORD_MANUAL_BUILD_WEBHOOK_URL }}
        run: |
          TEMPLATE="${{ env.NEW_BRANCH == 'dev-c3' && 'discord_template_notify_dev_public.json' || 'discord_template_notify_dev_private.json' }}"
          export EXTRA_VERSION_IDENTIFIER="${{ env.EXTRA_VERSION_IDENTIFIER }}"
          export VERSION="${{ env.VERSION }}"
          cat release/ci/${TEMPLATE} | envsubst > payload.json
          curl -X POST -H "Content-Type: application/json" -d @payload.json $DISCORD_WEBHOOK